### ISSUE TITLE
Integrate permissions model

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#1237]
Let's integrate new permission model from `http.secutiry` package step by step:

- [x] remove unused `Users` interface and implementations #1239 
- [x] cache authenticated users properly #1243 
- [x] implement authentication from storage with new users yaml files structure support #1246 
- [x] update http and files-adapter and integrate new policy  (#1238)
- [x] re-implement resp-api method to update users (#1253)
- [x] implement resp-api method to manage roles (#1255)
- [x] update other adapters (done all)
- [x] implement docker permissions (in docker-adapter https://github.com/artipie/docker-adapter/issues/550)
- [x] prepare detailed policy and permissions documentation (#1257)
