### ISSUE TITLE
Integrate fixed pypi adapter

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#232]
Fix all critical pypi issues, release new version and integrate to Artipie.
 - [x] Fix publish and install: https://github.com/artipie/pypi-adapter/issues/33
 - [x] Support HTTP-basic auth: https://github.com/artipie/pypi-adapter/issues/47
 - [ ] Repo index response: https://github.com/artipie/pypi-adapter/issues/41

**Comment by 0crat** [comment]
The job [#232](https://github.com/artipie/artipie/issues/232) assigned to @artemlazarev[/z](https://www.0crat.com/u/artemlazarev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/46ac65b9-9a9d-46cb-bb2b-56bf85a01efa); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @artemlazarev[/z](https://www.0crat.com/u/artemlazarev) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@artemlazarev[/z](https://www.0crat.com/u/artemlazarev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.9`

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @artemlazarev[/z](https://www.0crat.com/u/artemlazarev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
