### ISSUE TITLE
Week#26

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#234]
To be implemented on [#26](https://github.com/artipie/artipie/milestone/2) week:
 - [x] Read-only Docker proxy: #237
 - [x] Cache for Maven-proxy: https://github.com/artipie/artipie/issues/236
 - [x] Metrics collect API: https://github.com/artipie/artipie/issues/231
 - [x] Integrate PyPi adapter: https://github.com/artipie/artipie/issues/232
 - [ ] Maven and NPM groups: https://github.com/artipie/artipie/issues/233

**Comment by g4s8** [comment]
@artipie/contributors FYI

**Comment by olenagerasimova** [comment]
@g4s8 I've created [week 26](https://github.com/artipie/rpm-adapter/milestone/2) milestone in RPM, I think I will create new milestone in rpm for the next week each Friday to make planing more transparent

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#234` is not assigned, can't get performer
