### ISSUE TITLE
Week#27

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#248]
This is the plan for `#27` week:
 - [x] - Atomic save of file storage: #249
 - [x] - Simple metrics collector in-memory implementation: #231
 - [x] - Groups implementation: #233
 - [ ] - Caching Docker proxy: #250

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#248` is not assigned, can't get performer
