### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#389]
There're no integration tests in Artipie module. Let's create tests to verify each module works correctly. Each test may look like:
 - SetUp: and prepare configuration for server, start server
 - Run test case against repository, verify responses and data in storage if needed
 - TearDown: stop the server

Test cases:
 - [x] - Docker can push and pull image: https://github.com/artipie/artipie/issues/449
 - [x] - Maven can deploy and install dependencies https://github.com/artipie/artipie/issues/535
 - [x] - Curl can upload and download binary files https://github.com/artipie/artipie/issues/603
 - [x] - NuGet can upload and install packages https://github.com/artipie/artipie/issues/602
 - [x] - RPM can upload and install packages https://github.com/artipie/artipie/issues/604
 - [x] - PyPi can upload and download artifacts: https://github.com/artipie/artipie/issues/652
 - [x] - NPM local can publish and install packages: https://github.com/artipie/artipie/issues/605
 - [x] - Pypi proxy IT #715 
 - [x] - NPM proxy can install packages: https://github.com/artipie/artipie/issues/712
 - [x] - Helm can upload and install charts https://github.com/artipie/artipie/issues/607
 - [x] - Gem can upload and install gems https://github.com/artipie/artipie/issues/606

@artipie/contributors feel free to suggest improvements to this ticket if something is not correct or missed.
