### ISSUE TITLE
Week#31

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#391]
The draft of plan for week `#31` 2020 year:
 - [ ] - Repo and user limits: restrict repo size in settings and user's traffic per minute?
 - [x] - Move current HTTP implementation into `artipie/http-client` repository: https://github.com/artipie/http-client/issues/1
 - [x] - Fix and release NPM adapter: https://github.com/artipie/npm-adapter/issues/90
 - [ ] - Move storage locks from RPM to ASTO: https://github.com/artipie/asto/issues/214
 - [x] - PyPi improvements: https://github.com/artipie/pypi-adapter/milestone/4

@artipie/contributors feel free to suggest more items here

**Comment by olenagerasimova** [comment]
@g4s8 please see https://github.com/artipie/pypi-adapter/milestone/4

**Comment by olegmoz** [comment]
@g4s8 please add copying of lock from RPM to ASTO

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#391` is not assigned, can't get performer
