### ISSUE TITLE
Week#32

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#414]
This is a plan for `#32` week of 2020:
 - [x] Add some Artifactory API for backward compatibility: https://github.com/artipie/artipie/issues/413
 - [ ] Storage locking system https://github.com/artipie/asto/issues/214
 - [x] Improve Maven deploy workflow: https://github.com/artipie/maven-adapter/issues/117
 - Publish repository size metrics to Artipie dashboard #425
 - Fix critical issues in proxy repositories

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#414` is not assigned, can't get performer
