### ISSUE TITLE
Week#33

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#432]
This is the plan for `#33` week of 2020:
 - [x] Validate Maven artifacts on upload: https://github.com/artipie/maven-adapter/issues/125
 - [x] HTTP client for files-proxy repository: https://github.com/artipie/files-adapter/issues/19
 - [x] HTTP client for Maven adapter: https://github.com/artipie/maven-adapter/issues/128
 - [x] HTTP client for Docker adapter: https://github.com/artipie/docker-adapter/issues/304
 - [x] Aggregate and show published metrics from storage if enabled #425
 - [x] Implement storage locking system: https://github.com/artipie/asto/issues/214
 - [ ] Publish client benchmarks with charts to GH pages: https://github.com/artipie/artipie/issues/431

@artipie/contributors FYI

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#432` is not assigned, can't get performer
