### ISSUE TITLE
Week#34

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#450]
This is the plan for `#34` week of 2020:
 - [x] Fix OutOfMemory error in auth: https://github.com/artipie/artipie/issues/442
 - [ ] Fix VertX connection loosing: https://github.com/artipie/artipie/issues/443
 - [ ] Artifactory API support for users and permissions: https://github.com/artipie/artipie/issues/444
 - [x] Lock expiration in ASTO: https://github.com/artipie/asto/issues/231
 - [ ] Maven proxy cache verification: https://github.com/artipie/maven-adapter/issues/146
 - [x] Health check endpoints: https://github.com/artipie/artipie/issues/392

@artipie/contributors, @jeffzhu503  FYI

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#450` is not assigned, can't get performer
