### ISSUE TITLE
Week#35

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#488]
This is the plan for `#35` week of 2020:
 - [x] Artifactory API support for users and permissions: https://github.com/artipie/artipie/issues/444
 - [x] Maven proxy cache verification: https://github.com/artipie/maven-adapter/issues/146
 - [x] Add integration tests for Docker: https://github.com/artipie/artipie/issues/449
 - [x] Avoid unnecessary metadata updates in Maven: https://github.com/artipie/maven-adapter/issues/144
 - [x] Permissions support in Gem adapter: https://github.com/artipie/gem-adapter/issues/45
 - [x] Use locks with expiration in RPM adapter: https://github.com/artipie/rpm-adapter/issues/340

@artipie/contributors, @jeffzhu503  FYI

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#488` is not assigned, can't get performer

**Comment by g4s8** [comment]
@rultor release, tag=`0.10`
