### ISSUE TITLE
Compatibility with existing products

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#575]
The following issues need to be addressed to make HTTP API compatible with existing products:

- [x] List files/folders API endpoint: https://github.com/artipie/artipie/issues/545
- [x] Add emails to users https://github.com/artipie/artipie/issues/569
- [x] Permission aliases in HTTP API: https://github.com/artipie/artipie/issues/574
- [x] Repositories on own ports: https://github.com/artipie/artipie/issues/570
- [x] "include-patterns" support in permissions API: https://github.com/artipie/artipie/issues/571
- [x] User groups support: https://github.com/artipie/artipie/issues/573
- [x] Readers group support: https://github.com/artipie/artipie/issues/572

**Comment by olegmoz** [comment]
@jeffzhu503 please see the issues. We are planning to address them so migration from existing products to Artipie would be seamless

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#575` is not assigned, can't get performer
