### ISSUE TITLE
Week#38

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#583]
This is the plan for `#38` week of 2020:
- [x] List files/folders API endpoint: https://github.com/artipie/artipie/issues/545
- [x] Add emails to users https://github.com/artipie/artipie/issues/569
- [x] Permission aliases in HTTP API: https://github.com/artipie/artipie/issues/574
- [ ] Repositories on own ports: https://github.com/artipie/artipie/issues/570
- [ ] User groups support: https://github.com/artipie/artipie/issues/573
- [ ] Maven integration tests https://github.com/artipie/artipie/issues/535

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#583` is not assigned, can't get performer
