### ISSUE TITLE
Week#39

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#614]
This is the plan for `#39` week of 2020:
- [x] Repositories on own ports: https://github.com/artipie/artipie/issues/570
- [x] "include-patterns" support in permissions API: https://github.com/artipie/artipie/issues/571
- [x] User groups support: https://github.com/artipie/artipie/issues/573
- [x] Readers group support: https://github.com/artipie/artipie/issues/572
- [x] Maven integration tests https://github.com/artipie/artipie/issues/535

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#614` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.11`

**Comment by olegmoz** [comment]
@yegor256 please help us out with release, `.rultor.yml` needs to be touched

**Comment by olegmoz** [comment]
@yegor256 we cannot create new release, please touch `.rultor.yml`

**Comment by yegor256** [comment]
@olegmoz done

**Comment by olegmoz** [comment]
@yegor256 thanks!

**Comment by olegmoz** [comment]
@rultor release, tag=`0.11`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.11.1`
