### ISSUE TITLE
Week#40

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#642]
This is the plan for `#40` week of 2020:
- [x] Fix Maven proxy and enable tests: https://github.com/artipie/artipie/issues/628
- [x] Publish September release notes: https://github.com/artipie/blog.artipie.com/issues/5
- [x] Join NPM local & proxy projects: https://github.com/artipie/npm-adapter/issues/123
- [x] Fix integration tests in NPM repository: https://github.com/artipie/npm-adapter/issues/122
- [x] Binary repository integration tests: https://github.com/artipie/artipie/issues/603

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#642` is not assigned, can't get performer
