### ISSUE TITLE
Week#41

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#654]
This is the plan for `#41` week of 2020:

 - [x] NuGet can upload and install packages https://github.com/artipie/artipie/issues/602
 - [x] RPM can upload and install packages: https://github.com/artipie/artipie/issues/604
 - [x] Basic authentication support in HTTP client: https://github.com/artipie/http-client/issues/50
 - [x] Support authentication in `maven-adapter` proxy: https://github.com/artipie/maven-adapter/issues/204

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#654` is not assigned, can't get performer
