### ISSUE TITLE
Week#42

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#684]
This is the plan for `#42` week of 2020:

- [x] PyPi can upload and download artifacts: https://github.com/artipie/artipie/issues/652
- [x] Bearer authentication support in HTTP client: https://github.com/artipie/http-client/issues/51
- [x] Support authentication in `files-adapter` proxy: https://github.com/artipie/files-adapter/issues/37
- [x] Update and document Maven proxy configuration: https://github.com/artipie/artipie/issues/608
- [x] Index endpoint in PyPi proxy: https://github.com/artipie/pypi-adapter/issues/128

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#684` is not assigned, can't get performer
