### ISSUE TITLE
Week#43

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#697]
This is the plan for `#43` week of 2020:

- [x] Multiple remotes in Maven proxy: https://github.com/artipie/artipie/issues/694
- [x] Authentication for files proxy remote : https://github.com/artipie/artipie/issues/692
- [x] Missing metadata fields in NPM: https://github.com/artipie/npm-adapter/issues/119
- [x] Search command support in PyPi: https://github.com/artipie/pypi-adapter/issues/135
- [x] PyPi proxy for artifacts: https://github.com/artipie/pypi-adapter/issues/129
- [x] PyPi proxy authentication: https://github.com/artipie/pypi-adapter/issues/130

**Comment by olegmoz** [comment]
@olenagerasimova please see the draft, what issues were you planning to complete next week in PyPi?

**Comment by olenagerasimova** [comment]
@olegmoz these three:
- support pip search https://github.com/artipie/pypi-adapter/issues/135
- proxy for artifacts https://github.com/artipie/pypi-adapter/issues/129
- proxy auth https://github.com/artipie/pypi-adapter/issues/130

**Comment by olegmoz** [comment]
@olenagerasimova thanks, added the items to the plan

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#697` is not assigned, can't get performer
