### ISSUE TITLE
Week#44

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#711]
This is the plan for `#44` week of 2020:

- [x] October release notes: https://github.com/artipie/blog.artipie.com/issues/7
- [x] NPM local can publish and install packages: https://github.com/artipie/artipie/issues/605
- [x] Maven proxy response when not found: https://github.com/artipie/maven-adapter/issues/219
- [x] RPM: Unpack and parse only newly added rpm packages https://github.com/artipie/rpm-adapter/issues/318 
- [x] RPM: Properly handle errors with metadata xml https://github.com/artipie/rpm-adapter/issues/323
- [x] RPM: instrument to properly verify correctness of repomd.xml https://github.com/artipie/rpm-adapter/issues/359
- [ ] Prepare to extract Artipie API into separate module: https://github.com/artipie/artipie/issues/713

**Comment by olenagerasimova** [comment]
RPM:
- unpack and parse only newly added rpm packages https://github.com/artipie/rpm-adapter/issues/318 
- properly handle errors with metadata xml https://github.com/artipie/rpm-adapter/issues/323
- instrument to properly verify repomd.xml https://github.com/artipie/rpm-adapter/issues/359
- also I think I'll dive in into rpm again and come up with some general plan to fully migrate to incremental update

**Comment by olenagerasimova** [comment]
@olegmoz please check RPM plans above, also I'd like to take issue https://github.com/artipie/artipie/issues/713 in artipie

**Comment by genryxy** [comment]
@olegmoz I can fix `MavenProxySlice` response next week artipie/maven-adapter#219

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy thanks, added issues to the plan

**Comment by olegmoz** [comment]
@rultor release, tag=`0.12`

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#711` is not assigned, can't get performer
