### ISSUE TITLE
Week#45

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#727]
This is the plan for #45 week of 2020:

- [x] Migrate Docker adapter to Java 8: https://github.com/artipie/docker-adapter/issues/341
- [x] Support absent content in proxies cache: https://github.com/artipie/asto/issues/286
- [x] Handle redirects in PyPi proxy: https://github.com/artipie/pypi-adapter/issues/145
- [x] Incremental update test coverage: https://github.com/artipie/rpm-adapter/issues/227
- [x] Do not throw IOExceptions in Settings: https://github.com/artipie/artipie/issues/729
- [x] Special symbols in NPM artifact names: https://github.com/artipie/npm-adapter/issues/139
- [x] NPM proxy integration tests: https://github.com/artipie/artipie/issues/712

**Comment by olenagerasimova** [comment]
@olegmoz for the next week
- return Optional of Content from cache https://github.com/artipie/asto/issues/286
- properly handle redirects in python-proxy https://github.com/artipie/pypi-adapter/issues/145
- strong testing in rpm https://github.com/artipie/rpm-adapter/issues/227

**Comment by genryxy** [comment]
@olegmoz for the next week

- Fix a regex bug artipie/npm-adapter#139
- Add npm proxy integration test #712

**Comment by olenagerasimova** [comment]
@olegmoz I'd suggest adding #729 to the plan

**Comment by olegmoz** [comment]
@olenagerasimova thanks, added

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#727` is not assigned, can't get performer
