### ISSUE TITLE
Week#46

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#742]
This is the plan for #46 week of 2020:

- [x] Docker: blobs with same content should not be overwritten: https://github.com/artipie/docker-adapter/issues/344
- [x] Remove deprecated auth classes usage: https://github.com/artipie/artipie/issues/700
- [x] Helm integration tests: https://github.com/artipie/artipie/issues/607
- [x] Blog post about Maven: https://github.com/artipie/blog.artipie.com/issues/10
- [ ] Refactoring REST API to not depend on `Settings`: https://github.com/artipie/artipie/issues/730 
- [x] Support absent content in PyPi proxy: https://github.com/artipie/pypi-adapter/issues/149
- [x] Support absent content in Maven proxy: https://github.com/artipie/maven-adapter/issues/222

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit your plans for next week in comments

**Comment by olenagerasimova** [comment]
@olegmoz please, consider these tasks:
- finish support absent content in proxies cache implementation artipie/asto#286 
- support absent content in python proxy https://github.com/artipie/pypi-adapter/issues/149
- support absent content in maven proxy https://github.com/artipie/maven-adapter/issues/222
- also I'd take this issue as part of the extracting API into separate repo https://github.com/artipie/artipie/issues/730
