### ISSUE TITLE
Week#47

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#750]
This is the plan for #47 week of 2020:

- [x] Docker should store data in storage root: https://github.com/artipie/docker-adapter/issues/346
- [x] Non-blocking NuGet adapter: https://github.com/artipie/nuget-adapter/issues/117
- [x] Prepare Python blog post: https://github.com/artipie/blog.artipie.com/issues/12
- [x] Tests for index generation in Helm adapter: https://github.com/artipie/helm-adapter/issues/77
- [x] Gem integration tests: https://github.com/artipie/artipie/issues/606
- [ ] Transfer management API and dashboard to separate repository: https://github.com/artipie/management-api/issues/1

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit your plans for next week in comments

**Comment by olenagerasimova** [comment]
@olegmoz I'm planning to 
- start python blog post https://github.com/artipie/blog.artipie.com/issues/12 
- transfer API into new repo https://github.com/artipie/management-api/issues/1

**Comment by genryxy** [comment]
@olegmoz I'm planning to add tests to verify the content of `index.yaml` artipie/helm-adapter#77

**Comment by olenagerasimova** [comment]
@olegmoz I do not think I will transfer API and dashboard this week, can we change the plan a bit and take artipie/management-api#2 instead of artipie/management-api#1?

**Comment by olegmoz** [comment]
@olenagerasimova thanks for raising this concern in advance. I do not think we need to update the plan, it's not end of the world if some objectives are not reached by the end of the week. Let's just do the planning better next time
