### ISSUE TITLE
Week#48

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#766]
This is the plan for #48 week of 2020:

- [x] Configurable Docker storage layout: https://github.com/artipie/docker-adapter/issues/349
- [x] Subdirectories in RPM repository: https://github.com/artipie/rpm-adapter/issues/376
- [x] Minimal support for Bearer authentication: https://github.com/artipie/http/issues/261
- [x] Support authentication in Gem repositories: https://github.com/artipie/artipie/issues/768
- [x] API endpoints from new repository in Artipie: https://github.com/artipie/artipie/issues/761
- [x] Publish Python blog post: https://github.com/artipie/blog.artipie.com/issues/9

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit your plans for next week in comments

**Comment by olenagerasimova** [comment]
@olegmoz for the next week I'd suggest to replace 
- Transfer management API and dashboard to separate repository: artipie/management-api#1

with 

- API endpoints from new `managent-api` repository in Artipie https://github.com/artipie/artipie/issues/761

As for other plans, I want to finish python article and fix/release RPM

**Comment by olegmoz** [comment]
@olenagerasimova thanks, updated
