### ISSUE TITLE
Week#49

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#773]
This is the plan for #49 week of 2020:

- [x] Docker Bearer authentication: https://github.com/artipie/docker-adapter/issues/353
- [x] Extract class for layout in Artipie: https://github.com/artipie/artipie/issues/586
- [x] November release notes: https://github.com/artipie/blog.artipie.com/issues/14
- [x] Add test to verify authentication in Helm artipie/helm-adapter#57
- [x] Support Basic authentication in Gem artipie/gem-adapter#81

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit your plans for next week in comments

**Comment by olenagerasimova** [comment]
@olegmoz I'm having vacation next week, should I submit some plans for the week 50?

**Comment by olegmoz** [comment]
@olenagerasimova yes, please. It would be great to have the plans for week 50

**Comment by olenagerasimova** [comment]
@olegmoz here is the list for the week 50:
- Transfer `GetStorageSlice` https://github.com/artipie/management-api/issues/15
- Transfer dashboard https://github.com/artipie/management-api/issues/16
- Finish this one https://github.com/artipie/management-api/issues/14 (test for cookies auth is missing) 
- Add IT for API https://github.com/artipie/artipie/issues/775 

We also have some issues with auth in API (I've described it in #775 ), I think should discuss and document how it should work and fix it then. 

As for the list, I'm not sure it's possible to cover all of it in a week, feel free to prioritize.

**Comment by genryxy** [comment]
@olegmoz for the next week
- Add test to verify authentication in Helm artipie/helm-adapter#57
- Support Basic authentication in Gem artipie/gem-adapter#81
