### ISSUE TITLE
Week#50

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#793]
This is the plan for #50 week of 2020:

- [x] Docker local catalogs listing: https://github.com/artipie/docker-adapter/issues/374
- [x] Docker local tags listing: https://github.com/artipie/docker-adapter/issues/373
- [ ] NPM proxy misplaced libraries: https://github.com/artipie/artipie/issues/738
- [x] Remove deprecated auth classes usage in Gem https://github.com/artipie/gem-adapter/issues/83
- [ ] Transfer storage listing to management API https://github.com/artipie/management-api/issues/15
- [x] Transfer dashboard to management API https://github.com/artipie/management-api/issues/16
- [x] Fix cookie authentication in management API https://github.com/artipie/management-api/issues/14
- [x] Add integration tests for management API https://github.com/artipie/artipie/issues/775

**Comment by genryxy** [comment]
@olegmoz I am planning to work on this task next week https://github.com/artipie/gem-adapter/pull/82/files#diff-07305154310f5773909917626cfa11054bd244ce1078ac0c72d11c65b51f86b4L34
So, one of my assignments for next week:
Remove deprecated auth classes in Gem (the issue has not been created automatically yet)

**Comment by olegmoz** [comment]
@genryxy thanks, since there is no issue created it's problematic to add it to the plan

**Comment by genryxy** [comment]
@olegmoz I created a new issue for this task artipie/gem-adapter#83
