### ISSUE TITLE
Week#51

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#800]
This is the plan for #51 week of 2020:

- [x] Docker: mount blob endpoint: https://github.com/artipie/docker-adapter/issues/390 
- [x] Docker: mount blob in local repository: https://github.com/artipie/docker-adapter/issues/394
- [x] Support .yml and .yaml extensions for configs: https://github.com/artipie/artipie/issues/797
- [x] NPM proxy misplaced libraries: https://github.com/artipie/artipie/issues/738
- [x] Transfer storage listing to management API: artipie/management-api#15
- [x] Properly handle invalid repo configs on start: https://github.com/artipie/artipie/issues/804

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit you plans for next week

**Comment by genryxy** [comment]
@olegmoz I am planning to deal with this task next week
Support both extensions .yaml and .yml for config files #797

**Comment by olenagerasimova** [comment]
@olegmoz I'll take
- Transfer storage listing to management API artipie/management-api#15
- Properly handle invalid repo configs on start #804 
- Specify layout when ArtipieServer instance is created #803 

Also, as we discussed support for other repositories with Yegor last week, maybe I can start to investigate one of them.
