### ISSUE TITLE
Week#52

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#812]
This is the plan for #52 week of 2020:

- [x] Support `.yml` and `.yaml` extensions for configs: https://github.com/artipie/management-api/issues/27
- [x] Debian project setup: https://github.com/artipie/debian-adapter/issues/1
- [x] Debian project CI: https://github.com/artipie/debian-adapter/issues/6
- [x] Debian install integration test: https://github.com/artipie/debian-adapter/issues/2
- [x] Docker catalog cache: https://github.com/artipie/docker-adapter/issues/367
- [x] Docker tags proxy: https://github.com/artipie/docker-adapter/issues/375

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit you plans for next week

**Comment by genryxy** [comment]
@olegmoz I am planning to deal with this task next week
Support .yml and .yaml extensions for configs in management-api module: artipie/management-api#27

**Comment by olenagerasimova** [comment]
@olegmoz I'll continue to implement debian repo, issues list is here https://github.com/artipie/debian-adapter/issues

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#812` is not assigned, can't get performer
