### ISSUE TITLE
Week#53

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#825]
This is the plan for #53 week of 2020:

- [x] December release notes: https://github.com/artipie/blog.artipie.com/issues/16
- [x] Docker: tags in proxy: https://github.com/artipie/docker-adapter/issues/354
- [x] Docker: image level permissions: https://github.com/artipie/docker-adapter/issues/417
- [ ] Fix Gem proof: https://github.com/artipie/artipie/issues/813
- [ ] Debian: create/update Packages files: https://github.com/artipie/debian-adapter/issues/11

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit you plans for next week

**Comment by olenagerasimova** [comment]
@olegmoz 
push to debian, I'm not sure it will be fully implemented next week, I'll try to divide implementation to subtasks. Also, it seems that we have to publish release notes next week

**Comment by olegmoz** [comment]
@olenagerasimova we may settle on something small like adding an integration test for pushing a package

**Comment by genryxy** [comment]
@olegmoz I can try to fix gem proof
Fix Gem proof #813

**Comment by olenagerasimova** [comment]
@olegmoz let's take this https://github.com/artipie/debian-adapter/issues/11 issue for the next week

**Comment by olegmoz** [comment]
@rultor release, tag=`0.14`

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#825` is not assigned, can't get performer
