### ISSUE TITLE
Week#2

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#831]
This is the plan for #2 week of 2021:

- [x] Docker: Optimized upload for single chunk: https://github.com/artipie/docker-adapter/issues/424
- [x] Compatibility with docker granular permissions: https://github.com/artipie/artipie/issues/832
- [x] Debian: create/update Packages files: https://github.com/artipie/debian-adapter/issues/11
- [x] Debian: IT for push and install: https://github.com/artipie/debian-adapter/issues/19
- [x] Helm: Implement removing chart from index.yaml file: https://github.com/artipie/helm-adapter/issues/84

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit you plans for next week

**Comment by olenagerasimova** [comment]
@olegmoz 
- Debian: create/update Packages files: artipie/debian-adapter#11 (from the last week)
- IT for push and then install https://github.com/artipie/debian-adapter/issues/19

**Comment by genryxy** [comment]
@olegmoz 
Helm: Implement removing chart from index.yaml file: artipie/helm-adapter#84

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#831` is not assigned, can't get performer
