### ISSUE TITLE
Week#3

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#834]
This is the plan for #3 week of 2021:

- [x] PHP: Non-blocking repository implementation: https://github.com/artipie/composer-adapter/issues/66
- [x] PHP: HTTP endpoints should not interact with `Storage`: https://github.com/artipie/composer-adapter/issues/67
- [x] NuGet: HTTP endpoints should not interact with `Storage`: https://github.com/artipie/nuget-adapter/issues/124
- [x] Debian adapter in Artipie: https://github.com/artipie/artipie/issues/835
- [x] Helm: merges multiple `index.yaml` files: https://github.com/artipie/helm-adapter/issues/89
- [x] Helm: obtains `index.yaml` file based on the prefix: https://github.com/artipie/helm-adapter/issues/90

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy please submit you plans for next week

**Comment by olenagerasimova** [comment]
@olegmoz 
- add debian to Artipie (with proof and IT) https://github.com/artipie/artipie/issues/835
- smth from npm??

**Comment by genryxy** [comment]
@olegmoz I am planning to deal with these tasks next week
-  Helm: merges multiple `index.yaml` files: artipie/helm-adapter#89
-  Helm: obtains `index.yaml` file based on the prefix: artipie/helm-adapter#90

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#834` is not assigned, can't get performer
